### ISSUE TITLE
Home page as app

### ISSUE THREAD

**Issue by dannythomas13** [mkinawy/asp.net-core-mvc-pwa#1]
Hi
First of all thanks for publishing this, it was very quick and easy to get running and I was able to see how they can be installed. I noticed that once installed on mobile that contact and about page do not have address bar on the app but when navigating to the home page it does, any reason for this? Also is there a reason to have the 3 second delays on pages?

**Comment by mkinawy** [comment]
Hello @dannythomas13, and sorry for my late reply.

For the address bar thing, I think this is the browser's default behaviour when visiting the root of a progressive web app vs an inside page, not totally sure tho.

For the 3 sec thing, I did this to resemble an online live web call, localhost is fast of course so I want to see the pages like I'm browsing a real PWA empowered website.
